### ISSUE TITLE
PHP Warning on PHP 8.1 with new Woo PL translation

### ISSUE THREAD

**Issue by Torwald45** [iworks/omnibus#1]
After last Woocommerce PL translation update I see this Warning in logos:

`PHP Warning: Undefined array key "price" in /wp-content/plugins/omnibus/includes/iworks/omnibus/integration/class-iworks-omnibus-woocommerce.php on line 429`

**Comment by iworks** [comment]
Hi @Torwald45 

Could you check if there is still this warning? I can't reproduce.

Marcin
