### ISSUE TITLE
Incorrect Tax Inclusion in Displayed Prices

### ISSUE THREAD

**Issue by wkoszut** [iworks/omnibus#16]
I've encountered within the system where the tax inclusion settings do not seem to be functioning correctly.

Despite having the following tax options enabled:
- Include tax
- Display price with tax

When viewing the option "Display current regular price" along with the message "Lowest price from the last {days} days: {price}", the price that is displayed is the net price, not the gross price as expected.

However, when the "Display current promotional price" option is selected, the gross price is displayed correctly, with taxes included.

It appears there is a discrepancy in how the tax is applied in displaying regular prices versus promotional prices. This could lead to confusion for customers who expect tax to be included in all displayed prices as per the settings.

I would appreciate it if your team could investigate this issue and provide a resolution. If any further information or screenshots are required, please let me know, and I will be happy to provide them.

**Comment by iworks** [comment]
I the next version 4.0.0 there will be no choose of it. It cause too much problems. Price will be always the same like it is set in Woo.
