### ISSUE TITLE
Błąd typu E_PARSE po instalacji

### ISSUE THREAD

**Issue by mlodyno** [iworks/omnibus#2]
Po instalacji "Wystąpił błąd krytyczny w witrynie". Poniżej treść z raportu mailowego:

Do rozwiązania problemu, mogą być potrzebne poniższe dane:
WordPress w wersji 5.9.5
Aktualna wtyczka: Omnibus (wersja 2.3.2)
Wersja PHP: 7.2.34

Szczegóły błędu
===================
Błąd typu E_PARSE został spowodowany w linii 247 pliku /wp-content/plugins/omnibus/includes/iworks/omnibus/integration/class-iworks-omnibus-integration-woocommerce.php. Komunikat błędu: syntax error, unexpected ')'

**Comment by iworks** [comment]
Dziękuję za zgłoszenie - poprawione.

Typowy błąd dla PHP < 8, bo w 8 i wyżej to już nie błąd.
