### ISSUE TITLE
Call to a member function get_tax_class() on null

### ISSUE THREAD

**Issue by stalica** [iworks/omnibus#24]
Wersja 2.5.5 rzuca takim błędem (2.5.4 jest ok):

Fatal error: Uncaught Error: Call to a member function get_tax_class() on null in /wp-content/plugins/omnibus/includes/iworks/omnibus/class-iworks-omnibus-integration.php:338
Stack trace: #0 /wp-content/plugins/omnibus/includes/iworks/omnibus/integration/class-iworks-omnibus-integration-woocommerce.php(467): iworks_omnibus_integration->add_message()

**Comment by iworks** [comment]
It should be fixed in https://github.com/iworks/omnibus/releases/tag/2.5.6

**Comment by stalica** [comment]
Niestety nie pomogło, zmieniła się tylko linia błędu:
Fatal error: Uncaught Error: Call to a member function get_tax_class() on null in /wp-content/plugins/omnibus/includes/iworks/omnibus/class-iworks-omnibus-integration.php:339 Stack trace: #0 /wp-content/plugins/omnibus/includes/iworks/omnibus/integration/class-iworks-omnibus-integration-woocommerce.php(467): iworks_omnibus_integration->add_message()

**Comment by iworks** [comment]
> Niestety nie pomogło, zmieniła się tylko linia błędu: Fatal error: Uncaught Error: Call to a member function get_tax_class() on null in /wp-content/plugins/omnibus/includes/iworks/omnibus/class-iworks-omnibus-integration.php:339 Stack trace: #0 /wp-content/plugins/omnibus/includes/iworks/omnibus/integration/class-iworks-omnibus-integration-woocommerce.php(467): iworks_omnibus_integration->add_message()

poproszę o kontakt, bo to coś dziwnego .. 

marcin w domenie iworks w kraju pl

**Comment by iworks** [comment]
albo na fb - odnośnik jest w profilu: https://github.com/iworks
