### ISSUE TITLE
Finale Lite problem

### ISSUE THREAD

**Issue by czajnaklb** [iworks/omnibus#25]
Hello,

I have a following issue. The product history price looks like that

<img width="782" alt="Zrzut ekranu 2024-01-19 o 22 31 12" src="https://github.com/iworks/omnibus/assets/157172909/c94f20c8-acfd-4bfb-8ab0-159fdce7794f">

However, on the product page there is a different price displayed for the lowest in 30 days:
<img width="821" alt="Zrzut ekranu 2024-01-19 o 22 31 46" src="https://github.com/iworks/omnibus/assets/157172909/26785a76-012b-4c6b-abd1-520b23a880f4">

Why is it wrong?

This is a discount set with [Finale Lite](https://wordpress.org/plugins/finale-woocommerce-sales-countdown-timer-discount/) plugin for this product.

**Comment by iworks** [comment]
hi @czajnaklb 

How it's look when you turn off "Finale Lite" plugin?

M

**Comment by czajnaklb** [comment]
If I turn off "Finale Lite" plugin then there is no promotion set for this product, so nothing happens and there is only regular price displayed (which is correct).

**Comment by iworks** [comment]
hi @czajnaklb

I have been installed, but I'm unable to reproduce. What should I do to reproduce this issue?
