### ISSUE TITLE
`get_price_including_tax` deprecated

### ISSUE THREAD

**Issue by kanlukasz** [iworks/omnibus#26]
Cześć,

W ostatniej wersji używasz metody `get_price_including_tax()`, która jest już `deprecated`.
Dokładnie w 3 miejscach:
![image](https://github.com/iworks/omnibus/assets/30685349/c45a0564-c914-4cda-b66d-8af3b5ecf2b3)

To betonuje mi logi w tysiącach wpisów:
`PHP Deprecated:  Funkcja WC_Product::get_price_including_tax jest przestarzała od wersji 3.0! Zamiast jej proszę użyć wc_get_price_including_tax.`

Pytanie:
Czy do momentu wyjścia nowej wersji, wystarczy zmiana tej metody na funkcje `wc_get_price_including_tax()`?
I czy tylko zakładasz pierwszy argument jako obiekt klasy `WC_Product ` czy w drugim też przekazać jakieś dane?
Czy coś jeszcze do podmiany?

Po poprawce widzę to tak:
![image](https://github.com/iworks/omnibus/assets/30685349/13a1e9a8-6c7f-4730-abf8-9c523621a99c)

**Comment by iworks** [comment]
Hey @kanlukasz 

Masz rację, dlatego aktualna wersja dev nie zawiera już funkcji `get_price_including_tax()`.

Można ją wypróbować pobierając tutaj: https://github.com/iworks/omnibus/releases/tag/3.0.0.beta2

**Comment by kanlukasz** [comment]
Tyle to ja wiem :) Bardziej pytałem jaki widzisz tymczasowy fix bo zanim 3.0 wyjdzie to jeszcze pewnie minie trochę, a logi w serwisach mi puchną oporowo

> 
> Pytanie: Czy do momentu wyjścia nowej wersji, wystarczy zmiana tej metody na funkcje `wc_get_price_including_tax()`? I czy tylko zakładasz pierwszy argument jako obiekt klasy `WC_Product ` czy w drugim też przekazać jakieś dane? Czy coś jeszcze do podmiany?
> 
> Po poprawce widzę to tak: ![image](https://private-user-images.githubusercontent.com/30685349/304019765-13a1e9a8-6c7f-4730-abf8-9c523621a99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODUyNDYsIm5iZiI6MTcwODA4NDk0NiwicGF0aCI6Ii8zMDY4NTM0OS8zMDQwMTk3NjUtMTNhMWU5YTgtNmM3Zi00NzMwLWFiZjgtOWM1MjM2MjFhOTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDEyMDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMWZhMmY0NDJlYjlkOWZhOWM5NGI3OWI3NDQ2NjYwNDVjODcxMTVhM2Q5MWEyMDc0MWRkY2Q5Y2NiYzQwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nESJmMTjzzaHE255Lg0NUsIOtRzpC6uTuewqfXNviUQ)

**Comment by iworks** [comment]
W poniedziałek wydam :D
