### ISSUE TITLE
Możliwość edytowania cen z ostatnich 30 dni

### ISSUE THREAD

**Issue by mlodyno** [iworks/omnibus#7]
Są dwie sytuacje, które warto przewidzieć:
- duplikowanie produktów, czyli tworzenie nowych na podstawie starych - w tym wypadku najniższa cena z ost. 30 dni także jest kopiowana, co często jest niewskazane.
- pomyłkowe ceny. W przypadku gdy ktoś wpisze niewłaściwą cenę, mimo że obowiązywała na stronie przez chwilę, to wyświetlanie jej w historii cen nie będzie wskazane.

Rozwiązanie:
a) wyświetlanie historii ceny w edycji produktu, by móc jakąś pozycje usunąć,
b) po prostu umożliwić ręczne wpisanie ceny z 30 dni w edycji produktu.

**Comment by iworks** [comment]
cześć @mlodyno 

1. przy duplikowaniu faktycznie nie powinny się te informacje kopiować.
2. edycji nie przewiduję

Dziękuję!

Marcin
