### ISSUE TITLE
Duplicated array key in `settings_message` method

### ISSUE THREAD

**Issue by kanlukasz** [iworks/omnibus#8]
Nie wiem czy tu pisać w PL czy ENG, w każdym razie, chodzi mi o zwracaną tablicę:
![image](https://github.com/iworks/omnibus/assets/30685349/4bb2e98f-0304-41c2-bddf-e51fc52457e7)

Nie robię PR, bo nie wiem dokładnie jak chciałbyś to poprawić

**Comment by iworks** [comment]
usunę pierwszy - bo powielenie klucza w tablicy nadpisuje, więc jest dostępna tylko druga wartość.

dziękuję!

**Comment by iworks** [comment]
Z kodu usunięte, będzie w następnym wydaniu.
