### ISSUE TITLE
The price does not update depending on the selected variant.

### ISSUE THREAD

**Issue by zielonek252** [iworks/omnibus#9]
Hi, the price in omnibus does not change when we have discounted, for example, only one variant. The value remains this "lowest" of the other variant anyway. It also does not work dynamically when it reloads a variant. - omnibus price does not change

**Comment by iworks** [comment]
hi @zielonek252 

could you provide me more details about dynamic loading? theme maybe?

Marcin

**Comment by arvoisa** [comment]
We also tested this with default themes and its not working. You can reproduce it easily by making variable product and setting up different discounted prices for each variations. It will always show up the lowest price of them and does not update on selected variant.

**Comment by iworks** [comment]
It should be done with 3.0.2
